const actionType =  {
    GET_HOME : 'GET_HOME',
    SET_CUR_SONG_ID:'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA:'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID : 'SET_CUR_ALBUM_ID',
    LOADING :'LOADING',
    SET_RECENT_SONG : 'SET_RECENT_SONG',
    SEARCH : 'SEARCH',


    //music
    PLAY : 'PLAY',
    SET_ALBUM:'SET_ALBUM',
    PLAYLIST_ALBUM :'PLAYLIST_ALBUM',
    SCROLL : 'SCROLL'


}
export default actionType;